# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_books', '0002_auto_20171215_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entrys', to='address_books.Category'),
        ),
    ]
