# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-20 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address_books', '0003_auto_20171215_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='address_books.Category'),
        ),
    ]
